title: linuxpeople feed
description: Repository feed del canale Telegram @linuxpeople_feed
author: feed.linuxpeople.org Team
email: send@mirko.pm
url: https://feed.linuxpeople.org

assets: /assets
uploads: /uploads

permalink: /posts/:title/
markdown: kramdown

paginate: 5
paginate_path: "/:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

navigation:
    - link: "/"
      name: Home
    - link: "https://t.me/linuxpeople_feed"
      name: Canale Telegram
    - link: "https://t.me/linuxpeople"
      name: Community Telegram
    - link: "https://linuxpeople.org"
      name: "linuxpeople"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
